export const PROMO_PRESETS = [
  {
    id: "welcome_10",
    label: "Приветственный 10%",
    description: "10% на 30 дней, 1 использование",
    discountType: "percentage" as const,
    discountValue: 10,
    isSingleUse: true,
    maxUses: 1,
    daysValid: 30,
  },
  {
    id: "loyalty_15",
    label: "Лояльность 15%",
    description: "15% на 60 дней, до 3 использований",
    discountType: "percentage" as const,
    discountValue: 15,
    isSingleUse: false,
    maxUses: 3,
    daysValid: 60,
  },
  {
    id: "fixed_500",
    label: "Скидка 500 руб",
    description: "При заказе от 3 000 руб, 30 дней",
    discountType: "fixed_amount" as const,
    discountValue: 500,
    minOrderAmount: 3000,
    isSingleUse: true,
    maxUses: 1,
    daysValid: 30,
  },
  {
    id: "fixed_1000",
    label: "Скидка 1 000 руб",
    description: "При заказе от 5 000 руб, 30 дней",
    discountType: "fixed_amount" as const,
    discountValue: 1000,
    minOrderAmount: 5000,
    isSingleUse: true,
    maxUses: 1,
    daysValid: 30,
  },
]
